name: Versioning
on:
  push:
    branches: [main, canary]

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      currentVersion: ${{ steps.version.outputs.CURRENT_VERSION }}
      isFromCi: ${{ steps.check-release.outputs.IS_FROM_CI }}
    steps:
      - name: Setup Github Token as env
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 25
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Check if commit is from CI
        id: check-release
        run: |
          echo "IS_FROM_CI=$(echo '${{ github.event.head_commit.message }}' | grep -qE '\[ci skip\]|\[skip ci\]' && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Exit if commit is from CI
        if: steps.check-release.outputs.IS_FROM_CI == 'true'
        run: exit 0

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run version bump in txt file
        run: node scripts/version.js

      - name: Get version from txt file
        id: version
        run: |
          echo "VERSION=$(cat next-release-version.txt)" >> $GITHUB_OUTPUT

      - name: Cleanup txt files
        run: |
          rm next-release-version.txt
          rm next-release-gitTag.txt

      - name: Get current version from package.json
        id: currentVersion
        run: |
          echo "CURRENT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: If version is the same as in package.json, exit
        if: ${{steps.version.outputs.VERSION}} == ${{steps.currentVersion.outputs.CURRENT_VERSION}}
        run: exit 0

      - name: Authenticate the CI bot
        run: |
          git config user.name ProximaBot
          git config user.email github-actions@github.com

      - name: Update the version in monorepo root and packages
        run: |
          echo "Updating version in package.json ${{steps.version.outputs.VERSION}}"
          pnpm version ${{ steps.version.outputs.VERSION }}  --no-git-tag-version --workspaces-update=false --workspaces --include-workspace-root

      - name: Commit changes to the branch
        run: |
          git add -A
          git commit -m "[ci skip]: update version to ${{ steps.version.outputs.VERSION }}" --no-verify
          git push

      - name: Bundle and push the release to GitHub
        run: node scripts/release.js

  publish-particles-to-npm:
    needs: versioning
    runs-on: ubuntu-latest
    if: ${{ needs.versioning.outputs.isFromCi == 'false' }}
    steps:
      - name: Setup Github Token as env
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 25
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Validate in stdout
        run: echo "${{ steps.version.outputs.VERSION }} is going to be published to NPM"

      # - name: Build Particle
      #   run: pnpm run build --filter="@prxm/particles"
      # - name: Add token to .npmrc
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      # - name: Publish Particles
      #   run: pnpm run publish --filter="@prxm/particles"
